spring:
  application:
    name:  eureka-dicovery-service
    
server:  port: 3000
eureka:  client:    register-with-eureka: false
    fetch-registry: false
    service-url:      defaultZone: http://localhost:3000/eureka