spring:
  application:
    name: First-service
    
server:  port: 2002
  
eureka:  client:    register-with-eureka: true
    fetch-registry: true
    service-url:      defaultZone: http://localhost:2000/eureka